### ISSUE TITLE
Action is not catching errors!

### ISSUE THREAD

**Issue by Yagyansh** [GaneshSPatil/gocd-mergable#13]
Even if I add an invalid pipeline in my config-repository, the Github Action doesn't catch it and declares it fit to merge.

Sending the following files for config merge validations:
- deployment.gocd.yaml

 Performing preflight check...
 Success! Configurations can be merged successfully with GoCD.
 
 My YAML file.
 
```
 format_version: 3
pipelines:

  myname:
    group: ***
    label_template: ${COUNT}
    lock_behavior: none
    materials:
      dev:
        pipeline: ***
        stage: deploy
      build:
        pipeline: ***
        stage: build
      e2e:
        pipeline: ***
        stage: build
      k8s-deployment:
        git: ***
        shallow_clone: true
        auto_update: false
        branch: master
        destination: deployment
    environment_variables:
      ENVIRONMENT: ***
      APP_NAME: ***
    stages:
      - migration:
          fetch_materials: true
          approval:
            type: manual
            allow_only_on_success: false
          jobs:
            migration:
              elastic_profile_id: ***
              tasks:
                - fetch:
                    is_file: true
                    source: image_version
                    destination: deployment
                    pipeline: ***
                    -dev
                    -deployment
                    stage: build
                    job: build
                    run_if: passed
                - script: |
                       <commands>
      - deploy:
          fetch_materials: true
          approval:
            type: success
            allow_only_on_success: false
          jobs:
            deploy:
              timeout: 0
              elastic_profile_id: ***
              tasks:
                - fetch:
                    is_file: true
                    source: image_version
                    destination: deployment
                    pipeline: ***
                    -dev
                    -deployment
                    stage: build
                    job: build
                    run_if: passed
                - exec:
                    arguments:
                      - -c
                      - <command>
                    command: bash
                    run_if: passed
                    working_directory: deployment
```

This config has an error and it works fine if I try to run the preflight check API directly, but this passes via Github Actions.
